export interface ConversionPairInfo {
  id: string;
  fromFormat: string;
  toFormat: string;
  title: string;
  h1: string;
  description: string;
  badge: string;
  acceptedTypes: string[];
  outputFormat: 'webp' | 'jpeg' | 'png' | 'avif';
  category: 'image' | 'svg' | 'png' | 'jpg' | 'gif';
}

export const CONVERSION_PAIRS: Record<string, ConversionPairInfo> = {
  'heic-to-jpg': {
    id: 'heic-to-jpg',
    fromFormat: 'HEIC',
    toFormat: 'JPG',
    title: 'Convert HEIC to JPG Online — Free & Instant Photo Converter',
    h1: 'Convert HEIC to JPG Images',
    description: 'Transform iPhone & iPad HEIC photos into universal JPG images instantly. 100% in-browser processing with zero quality loss.',
    badge: 'iOS Photo',
    acceptedTypes: ['.heic', '.heif', 'image/heic', 'image/heif'],
    outputFormat: 'jpeg',
    category: 'image',
  },
  'webp-to-png': {
    id: 'webp-to-png',
    fromFormat: 'WebP',
    toFormat: 'PNG',
    title: 'Convert WebP to PNG Online — High Quality & Transparent',
    h1: 'Convert WebP to PNG Format',
    description: 'Convert WebP graphics into uncompressed, transparent PNG files for graphics editing, print, and design tools.',
    badge: 'High Quality',
    acceptedTypes: ['.webp', 'image/webp'],
    outputFormat: 'png',
    category: 'image',
  },
  'webp-to-jpg': {
    id: 'webp-to-jpg',
    fromFormat: 'WebP',
    toFormat: 'JPG',
    title: 'Convert WebP to JPG Online — Universal Photo Converter',
    h1: 'Convert WebP to JPG Images',
    description: 'Quickly change WebP web images into standard JPG photos compatible with all web browsers and photo viewers.',
    badge: 'Universal',
    acceptedTypes: ['.webp', 'image/webp'],
    outputFormat: 'jpeg',
    category: 'image',
  },
  'png-to-jpg': {
    id: 'png-to-jpg',
    fromFormat: 'PNG',
    toFormat: 'JPG',
    title: 'Convert PNG to JPG Online — Compress File Size Fast',
    h1: 'Convert PNG to JPG Images',
    description: 'Reduce image file sizes by converting transparent PNG graphics into lightweight JPG files with target size limits.',
    badge: 'Smaller File',
    acceptedTypes: ['.png', 'image/png'],
    outputFormat: 'jpeg',
    category: 'png',
  },
  'png-to-svg': {
    id: 'png-to-svg',
    fromFormat: 'PNG',
    toFormat: 'SVG',
    title: 'Convert PNG to SVG Online — High Precision Vector Converter',
    h1: 'Convert PNG to SVG Vector Format',
    description: 'Transform PNG graphics and logos into clean vector graphics format for scalable web icons and design software.',
    badge: 'Vector Trace',
    acceptedTypes: ['.png', 'image/png'],
    outputFormat: 'png',
    category: 'svg',
  },
  'svg-to-png': {
    id: 'svg-to-png',
    fromFormat: 'SVG',
    toFormat: 'PNG',
    title: 'Convert SVG to PNG Online — High Resolution Rasterizer',
    h1: 'Convert SVG to PNG Images',
    description: 'Rasterize SVG vector illustrations into high-resolution transparent PNG images for social media and web publishing.',
    badge: 'Rasterize',
    acceptedTypes: ['.svg', 'image/svg+xml'],
    outputFormat: 'png',
    category: 'svg',
  },
  'svg-to-jpg': {
    id: 'svg-to-jpg',
    fromFormat: 'SVG',
    toFormat: 'JPG',
    title: 'Convert SVG to JPG Online — Web Photo Converter',
    h1: 'Convert SVG to JPG Format',
    description: 'Turn scalable SVG vectors into lightweight JPG image files for fast web page loading and photo galleries.',
    badge: 'Web Photo',
    acceptedTypes: ['.svg', 'image/svg+xml'],
    outputFormat: 'jpeg',
    category: 'svg',
  },
  'svg-to-webp': {
    id: 'svg-to-webp',
    fromFormat: 'SVG',
    toFormat: 'WebP',
    title: 'Convert SVG to WebP Online — Next-Gen Web Compression',
    h1: 'Convert SVG to WebP Images',
    description: 'Export SVG vector graphics into modern WebP format for next-generation web speed optimization.',
    badge: 'Modern Web',
    acceptedTypes: ['.svg', 'image/svg+xml'],
    outputFormat: 'webp',
    category: 'svg',
  },
  'png-to-webp': {
    id: 'png-to-webp',
    fromFormat: 'PNG',
    toFormat: 'WebP',
    title: 'Convert PNG to WebP Online — Next-Gen Image Converter',
    h1: 'Convert PNG to WebP Images',
    description: 'Compress PNG files into modern WebP format while preserving crystal-clear quality and transparency.',
    badge: 'Next-Gen',
    acceptedTypes: ['.png', 'image/png'],
    outputFormat: 'webp',
    category: 'png',
  },
  'png-to-avif': {
    id: 'png-to-avif',
    fromFormat: 'PNG',
    toFormat: 'AVIF',
    title: 'Convert PNG to AVIF Online — Ultra File Size Compression',
    h1: 'Convert PNG to AVIF Images',
    description: 'Achieve maximum compression efficiency by converting PNG images into AVIF format with zero visual degradation.',
    badge: 'Ultra Compress',
    acceptedTypes: ['.png', 'image/png'],
    outputFormat: 'avif',
    category: 'png',
  },
  'jpg-to-png': {
    id: 'jpg-to-png',
    fromFormat: 'JPG',
    toFormat: 'PNG',
    title: 'Convert JPG to PNG Online — High Resolution Image Converter',
    h1: 'Convert JPG to PNG Format',
    description: 'Convert JPG and JPEG camera photos into PNG graphics for editing, design tools, and web publishing.',
    badge: 'Transparent',
    acceptedTypes: ['.jpg', '.jpeg', 'image/jpeg'],
    outputFormat: 'png',
    category: 'jpg',
  },
  'jpg-to-webp': {
    id: 'jpg-to-webp',
    fromFormat: 'JPG',
    toFormat: 'WebP',
    title: 'Convert JPG to WebP Online — Fast Load Web Compression',
    h1: 'Convert JPG to WebP Images',
    description: 'Optimize JPEG photos into modern WebP files to boost page speed performance and Google Lighthouse scores.',
    badge: 'Fast Load',
    acceptedTypes: ['.jpg', '.jpeg', 'image/jpeg'],
    outputFormat: 'webp',
    category: 'jpg',
  },
  'gif-to-webp': {
    id: 'gif-to-webp',
    fromFormat: 'GIF',
    toFormat: 'WebP',
    title: 'Convert GIF to Animated WebP Online — 70% File Size Reduction',
    h1: 'Convert GIF to WebP Images',
    description: 'Compress heavy animated GIF files into lightweight animated WebP images with higher color precision.',
    badge: 'Animated WebP',
    acceptedTypes: ['.gif', 'image/gif'],
    outputFormat: 'webp',
    category: 'gif',
  },
  'gif-to-png': {
    id: 'gif-to-png',
    fromFormat: 'GIF',
    toFormat: 'PNG',
    title: 'Convert GIF to PNG Online — Extract Image Frames',
    h1: 'Convert GIF to PNG Images',
    description: 'Convert GIF animations into crisp, high-resolution static PNG graphics with transparent background support.',
    badge: 'Frame Extract',
    acceptedTypes: ['.gif', 'image/gif'],
    outputFormat: 'png',
    category: 'gif',
  },
  'gif-to-jpg': {
    id: 'gif-to-jpg',
    fromFormat: 'GIF',
    toFormat: 'JPG',
    title: 'Convert GIF to JPG Online — High Speed Converter',
    h1: 'Convert GIF to JPG Images',
    description: 'Extract and convert GIF images into standard JPG photo format for sharing and web publishing.',
    badge: 'First Frame',
    acceptedTypes: ['.gif', 'image/gif'],
    outputFormat: 'jpeg',
    category: 'gif',
  },
};
